*
* Consulta de Produtos
*

SAVE SCREEN TO TMP
ARROWS(.F.)
SELECT PRODUTO
SET ORDER TO 1
GO TOP
DECLARE MAT1[3],MAT2[3],MAT3[3]
MAT1[1] = "CODPROD"
MAT1[2] = "NOMEPROD"
MAT1[3] = "VALOR"
MAT2[1] = "C¢digo"
MAT2[2] = "Produto"
MAT2[3] = "Valor Unit."
MAT3[1] = "ÄÂÄ"
MAT3[2] = "ÄÂÄ"
MAT3[3] = "ÄÂÄ"
MOLDURA(12,01,21,76,STDMOLD,.T.,"Consulta de Produtos",STDINVE)
SETCOLOR(STDMOLD+","+STDINVE) 
SET CURSOR OFF
DBEDIT(13,02,20,75,MAT1,"","",MAT2,MAT3)
ARROWS(.T.)
RESTORE SCREEN FROM TMP
RETURN
