*
* Lista de Devedores
*

RESTORE SCREEN FROM ENTRASCR
SET CURSOR OFF
MOLDURA(08,22,14,57,STDMOLD,.T.,"Relatório de Devedores",STDINVE)
SELECT ALUNO
SET ORDER TO 2
GO  TOP
LINHA     = ""
LIN       = 01
COL       = 00
REGISTRO  = 01
TOTAL     = RECCOUNT()
GO TOP
KPRINT(@LIN,03,CHR(14)+"DEVEDORES")
KPRINT(@LIN,00,"")
DO WHILE .NOT. EOF()
   IF BLOQUEIO >= IF(TIPOPGTO = "S",2,IF(TIPOPGTO = "Q",4,IF(TIPOPGTO = "M",8,2)))
      LINHA = LINHA + CONTA + "  "
      COL   = COL + 1
   ENDIF
   PERCENT(IF(REGISTRO<>0,REGISTRO,1),IF(TOTAL<>0,TOTAL,1),11,25,30,1)
   REGISTRO = REGISTRO + 1
   SKIP +1
   IF COL = 3 .OR. EOF()
      KPRINT(@LIN,00,ALLTRIM(LINHA))
      COL   = 00
      LINHA = ""
   ENDIF
ENDDO
KRODAP(@LIN)
RESTORE SCREEN FROM ENTRASCR
RETURN
