*
* Emissao de Extrato
*

SAVE SCREEN TO TMP
DO WHILE .T.
   SELECT ALUNO
   SET ORDER TO 2
   MOLDURA(12,01,18,76,STDMOLD,.T.,"Emiss„o de Extrato",STDINVE)
   HCODIGO = 0
   @ 13,05 SAY "Entre com o N£mero:" GET HCODIGO PICTURE "9999"
   SET CURSOR ON
   READ
   SET CURSOR OFF
   IF LASTKEY() = 27 .OR. HCODIGO = 0
      EXIT
   ENDIF
   HNUMERO = STRZERO(HCODIGO,4,0)
   SEEK HNUMERO
   IF .NOT. FOUND()
      MESSAGE("Registro N„o Existe !!!")
      LOOP
   ENDIF
   MESSAGE()
   EXTRATO(HNUMERO,"CODIGO = HNUMERO")
ENDDO
RESTORE SCREEN FROM TMP
RETURN
