*
* Lista de Devedores/JUROS
*

RESTORE SCREEN FROM ENTRASCR
SET CURSOR OFF
MOLDURA(08,22,14,57,STDMOLD,.T.,"Devedores",STDINVE)
@ 11,25 SAY "Quantidade de Dias: " GET D_DIAS PICTURE "999"
SET CURSOR ON
READ
SET CURSOR OFF
IF LASTKEY() = 27
   RESTORE SCREEN FROM ENTRASCR
   RETURN
ENDIF
SAVE TO DATAS.MEM ALL LIKE D_*
@ 11,23 SAY ALIGN("Aguarde Impress„o...","C",34)
SELECT ALUNO
SET ORDER TO 2
GO  TOP
CABEC = CHR(18)+CHR(27)+"ERELATORIO DEVEDORES ANTIGOS"+CHR(27)+"F"
LIN       = 01
KPRINT(@LIN,26,CABEC)
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,"DATA: "+DTOC(DATE()))
KPRINT(@LIN,00,"")
DO WHILE .NOT. EOF()
   IF LIN >= 56
      KPRINT(59,00,REPLICATE("-",68)+" by arkhan")
      LIN=2
      EJECT
      KPRINT(@LIN,26,CABEC)
      KPRINT(@LIN,00,"")
      KPRINT(@LIN,00,"DATA: "+DTOC(DATE()))
      KPRINT(@LIN,00,"")
   ENDIF
   REGATU=RECNO()
   SELECT LANCAMEN
   SET ORDER TO 2
   GO  TOP
   SEEK ALUNO->CONTA
   IF FOUND()
      DATAPRI  = DATALCTO
      VALORTOT = 0
      DO WHILE CODIGO=ALUNO->CONTA
         VALORTOT = VALORTOT + VALOR
         SKIP +1
      ENDDO
      IF DATE() - DATAPRI >= 30
         KPRINT(@LIN,0,ALUNO->CONTA+"  "+CHR(27)+"G"+ALUNO->NOME+CHR(27)+"H  "+ALUNO->TELEFONE+"  "+;
                       DTOC(DATALCTO)+"  "+ALUNO->TIPOPGTO)
         KPRINT(@LIN,0,"      "+ALUNO->ENDERECO)
         KPRINT(@LIN,0,"      "+ALUNO->BAIRRO+"  "+ALUNO->CEP)
         KPRINT(@LIN,0,"      "+ALUNO->CIDADE+"  "+ALUNO->ESTADO)
         KPRINT(@LIN,0,CHR(27)+"G      TOTAL DE LCTOS.: "+TRANSFORM(VALORTOT,"9,999.99")+;
                       "  HAVER: "+TRANSFORM(ALUNO->CREDITO,"9,999.99")+;
                       "  DEVE A: "+STRZERO(DATE()-DATAPRI,4)+" DIAS"+CHR(27)+"H")
         KPRINT(@LIN,0,"")
      ENDIF
   ENDIF
   SELECT ALUNO
   GO     REGATU
   SKIP   +1
ENDDO
KPRINT(59,00,REPLICATE("-",68)+" by arkhan")
EJECT
RESTORE SCREEN FROM ENTRASCR
RETURN
