*
* Lista de Venda pagas no periodo
*

RESTORE SCREEN FROM ENTRASCR
SET CURSOR OFF
MOLDURA(08,22,14,57,STDMOLD,.T.,"Contas Pagas",STDINVE)
@ 11,23 SAY ALIGN("Aguarde Impress„o...","C",34)
SELECT MORTO
SET    ORDER TO 1
GO     TOP
CABEC        = CHR(27)+"E"+CHR(14)+"CONTAS PAGAS"+CHR(27)+"F"
LIN          = 1
TOTALUSUARIO = 0
TOTALGERAL   = 0
TOTALCONTA   = 0
CODATU       = CODIGO
USUATU       = USUARIO
KPRINT(@LIN,00,CABEC)
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,"USUARIO: "+CHR(27)+"E"+USUARIO+CHR(27)+"F")
DO WHILE .NOT. EOF()
   IF CODATU <> CODIGO .OR. USUATU <> USUARIO
      KPRINT(@LIN,00,"   "+CODATU+"   "+TRANSFORM(TOTALCONTA,"99,999.99"))
      TOTALCONTA = 0
      CODATU = CODIGO
   ENDIF
   IF USUATU <> USUARIO
      KPRINT(@LIN,00,"Total:    "+CHR(27)+"E"+TRANSFORM(TOTALUSUARIO,"99,999.99")+CHR(27)+"F")
      KPRINT(@LIN,00,"")
      KPRINT(@LIN,00,"")
      KPRINT(@LIN,00,"USUARIO: "+CHR(27)+"E"+USUARIO+CHR(27)+"F")
      TOTALUSUARIO = 0
      USUATU = USUARIO
   ENDIF
   TOTALUSUARIO = TOTALUSUARIO + VALOR
   TOTALGERAL   = TOTALGERAL   + VALOR
   TOTALCONTA   = TOTALCONTA   + VALOR
   SKIP +1
ENDDO
KPRINT(@LIN,00,"   "+CODATU+"   "+TRANSFORM(TOTALCONTA,"99,999.99"))
KPRINT(@LIN,00,"Total:    "+CHR(27)+"E"+TRANSFORM(TOTALUSUARIO,"99,999.99")+CHR(27)+"F")
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,CHR(27)+"EGeral:    "+TRANSFORM(TOTALGERAL,"99,999.99")+CHR(27)+"F")
KRODAP(@LIN)
IF TYPE("D_SENHA1") = "U"
   PUBLIC D_SENHA1
   @ 18,03 SAY "Definir Senha 1: "
   D_SENHA1 = PASSWORD(18,20,"*",".",4)
   SAVE TO DATAS.MEM ALL LIKE D_*   
ENDIF
IF TYPE("D_SENHA2") = "U"
   PUBLIC D_SENHA2
   @ 19,03 SAY "Definir Senha 2: "
   D_SENHA2 = PASSWORD(19,20,"*",".",4)
   SAVE TO DATAS.MEM ALL LIKE D_*
ENDIF

@ 17,03 SAY "Para apagar os registros do arquivo morto, digite as senhas:"
@ 18,03 SAY "Digite a senha 1:         "
@ 19,03 SAY "Digite a senha 2:         "
SENHA1 = .F.
SENHA2 = .F.

DIGITA1 = PASSWORD(18,21,"*",".",4)
IF D_SENHA1 = DIGITA1 .AND. LEN(D_SENHA1) = LEN(DIGITA1)
   SENHA1 = .T.
ENDIF

DIGITA2 = PASSWORD(19,21,"*",".",4)
IF D_SENHA2 = DIGITA2 .AND. LEN(D_SENHA2) = LEN(DIGITA2)
   SENHA2 = .T.
ENDIF

IF SENHA1 .AND. SENHA2
   IF FIL_LOCK(0)
      DELETE ALL
      UNLOCK ALL
   ENDIF
   @ 17,03 CLEAR TO 19,78
   IF CONFIRM("Desejam Alterar as senhas?",.F.)
      @ 18,03 SAY "Definir Senha 1: "
      D_SENHA1 = PASSWORD(18,20,"*",".",4)   
      @ 19,03 SAY "Definir Senha 2: "
      D_SENHA2 = PASSWORD(19,20,"*",".",4)
      SAVE TO DATAS.MEM ALL LIKE D_*
   ENDIF
ELSE
   @ 20,03 SAY "Alguma senha esta errada..."
   INKEY(0)
ENDIF
RESTORE SCREEN FROM ENTRASCR
RETURN
