*
* Segunda
*

RESTORE SCREEN FROM ENTRASCR
SET CURSOR OFF
SELECT ALUNO
SET    ORDER TO 1
GO     TOP
REGISTRO = 1
MOLDURA(08,22,14,57,STDMOLD,.T.,"Segunda",STDINVE)
DO WHILE .NOT. EOF()
   PERCENT(REGISTRO,IF(RECCOUNT()<>0,RECCOUNT(),1),11,25,30,1)
   IF BLOQUEIO > 0 .AND. BLOQUEIO < 9
      IF REC_LOCK(0)
         REPLACE BLOQUEIO WITH BLOQUEIO + 1
         UNLOCK
      ENDIF
   ENDIF
   SKIP +1
   REGISTRO = REGISTRO + 1
ENDDO
DO RELATOR
RESTORE SCREEN FROM ENTRASCR
RETURN
