*
* Sexta   -  Soma Semana... Se semana for maior que 1,2 ou 4 Soma bloqueio...
*

RESTORE SCREEN FROM ENTRASCR
SET CURSOR OFF
SELECT ALUNO
SET    ORDER TO 1
GO     TOP
TOTAL    = RECCOUNT()
REGISTRO = 1
MOLDURA(08,22,14,57,STDMOLD,.T.,"Sexta",STDINVE)
DO WHILE .NOT. EOF()
   XCODIGO  = CONTA
   VALORTOT = 0
   SELECT LANCAMEN
   PERCENT(REGISTRO,TOTAL,11,25,30,1)
   SUM VALOR TO VALORTOT FOR CODIGO = XCODIGO .AND. FLAG = 0
   SELECT ALUNO
   IF VALORTOT > CREDITO
      IF BLOQUEIO >= 0 .AND. BLOQUEIO < 9
         IF REC_LOCK(0)
            REPLACE BLOQUEIO WITH BLOQUEIO + 1
            UNLOCK
         ENDIF
      ENDIF
   ENDIF
   REGISTRO = REGISTRO + 1
   SKIP +1
ENDDO
IF FIL_LOCK(0)
   REPLACE ALL SALDOS WITH 0
   UNLOCK ALL
ENDIF
RESTORE SCREEN FROM ENTRASCR
RETURN
