FUNCTION KCONVERTE
PRIVATE LETR
PARAMETERS LETR
STR1 = "123456789.0"+CHR(13)+CHR(27)+CHR(13)
STR2 = "123456789"+CHR(27)+"0"+CHR(13)+CHR(01)+CHR(13)
RETURN(IF(AT(LETR,STR1) = 0,"",SUBSTR(STR2,AT(LETR,STR1),1)))

FUNCTION KINPUT
PRIVATE Y,X,TAM,EX,CR1,STR,CY,CX,INI,CONF
PARAMETERS Y,X,TAM,EX,INI,CONF
CR1 = SETCOLOR(STDALER)
@ 02,15 SAY "  Usu rio entre com as informa‡”es pelo teclado.  "
SETCOLOR("W/N")
@ 02,65 SAY "Ü"
@ 03,16 SAY REPLICATE("ß",50)
SETCOLOR(CR1)
INI  = IF(TYPE("INI" ) = "U","0",INI )
CONF = IF(TYPE("CONF") = "U",.F.,CONF)
CY  = ROW()
CX  = COL()
STR = ""
SET CURSOR OFF
SET COLOR TO N/W
@ Y,X SAY "_"+SPACE(TAM-2)+INI
DO WHILE .T.
   DO WHILE .T.
      TKEY = INKEY()
      IF FILE(DIRET+"\CONTROL.CLA")
         SAVE SCREEN TO TMPENTRA
         TMPCOR=SETCOLOR("N*/W")
         @ 11,01 SAY ALIGN("SISTEMA BLOQUEADO TEMPORARIAMENTE... AGUARDE...","C",78)
         SETCOLOR(TMPCOR)
         CLOSE ALL
         DO WHILE .NOT. FILE(DIRET+"\CONTROL.OPN")
         ENDDO
         SET DEFAULT TO &DIRET
         SELECT 1
         IF NET_USE("LANCAMEN",.F.,0)
            SET INDEX TO LANC001,LANC002
         ELSE
            WARNING("Erro ao abrir o arquivo LANCAMEN.DBF")
         ENDIF
         SELECT 2
         IF NET_USE("PRODUTO",.F.,0)
            SET INDEX TO PROD001
         ELSE
            WARNING("Erro ao abrir o arquivo PRODUTO.DBF")
         ENDIF
         SELECT 3
         IF NET_USE("ALUNO",.F.,5)
            SET INDEX TO ALUN001,ALUN002,ALUN003
         ELSE
            WARNING("Erro ao abrir o arquivo ALUNO.DBF")
         ENDIF 
         RESTORE SCREEN FROM TMPENTRA
         KEYBOARD "......"+CHR(13)+CHR(13)
      ENDIF
      IF TKEY <> 0
         EXIT
      ENDIF
   ENDDO
   T = CHR(TKEY)
   IF AT(T,"0123456789+."+CHR(13)+CHR(27)) = 0
      LOOP
   ENDIF
   IF T = "."
      IF .NOT. EMPTY(STR)
         STR = ""
         @ Y,X SAY "_"+SPACE(TAM-1)
         LOOP
      ELSE
         EXIT
      ENDIF
   ENDIF
   IF T = CHR(13)
      IF EMPTY(STR)
         STR = INI
      ENDIF
      EXIT
   ENDIF
   IF T = CHR(27)
      STR = "PHIL"
      EXIT
   ENDIF
   IF T = "+"
      STR = "TOTA"
      EXIT
   ENDIF
   IF CONF
      IF LEN(STR) < TAM
         STR = STR + T
      ENDIF
   ELSE
      STR = STR + T
   ENDIF
   @ Y,X SAY IF(EX,STR,REPLICATE("*",LEN(STR)))+IF(LEN(STR) < TAM,"_","")
   IF (.NOT. CONF) .AND. LEN(STR) = TAM
      EXIT
   ENDIF
ENDDO
STR = IF(STR="PHIL" .OR. STR="TOTA",STR,STRZERO(VAL(STR),TAM,0))
@ Y,X SAY IF(STR="PHIL" .OR. STR="TOTA",SPACE(TAM),IF(EX,STR,REPLICATE("*",TAM)))
SETCOLOR(STDMOLD+","+STDINVE)
@ 02,15 CLEAR TO 03,65
SETCOLOR(CR1)
@ CY,CX SAY ""
RETURN(STR)

FUNCTION KPRINT
PARAMETERS Y,X,STR
TELA = .F.
IF .NOT. ISPRINTER()
   DO WHILE .NOT. ISPRINTER()
      MESSAGE("Ligue a Impressora !!!",STDALER)
      IF INKEY() = 27
         TELA = .T.
         EXIT
      ENDIF
   ENDDO
ENDIF
MESSAGE()
IF .NOT. TELA
   SETPRC(Y-1,0)
   SET DEVICE TO PRINTER
ENDIF
@ Y,X SAY STR
SET DEVICE TO SCREEN
Y = Y + 1
RETURN(.F.)

FUNCTION KRODAP
PARAMETERS LIN
KPRINT(@LIN,00,REPLICATE("-",24))
FOR TMPRODAP = 1 TO 20
   KPRINT(@LIN,00,"")
NEXT TMPRODAP
SETPRC(1,0)
RETURN(.F.)

FUNCTION SOMATORIA
PRIVATE HCOD,ANTAREA,ANTORD,TOTAL4
PARAMETERS HCOD
ANTAREA = SELECT()
ANTORD  = INDEXORD()
SELECT  LANCAMEN
SUM ALL VALOR TO TOTAL4 FOR CODIGO = HCOD
SELECT(ANTAREA)
SET ORDER TO ANTORD
RETURN(TOTAL4)

FUNCTION ALEAT
PRIVATE TMP1,TMP2,TMP3,TMP4,TMP5,HSENHA
TMP5 = AL[1] + AL[2] + AL[3]
AL[INDAL] = RIGHT(STR(INT(SECONDS() * 100)),4)
INDAL     = INDAL + 1
IF INDAL > 3
   INDAL = 1
ENDIF
TMP1 = MOD(SECONDS()*100,LEN(TMP5)-2)
TMP2 = MOD(VAL(SUBSTR(TIME(),7,2)) + 1,LEN(TMP5)-2)
HSENHA = SUBSTR(TMP5,TMP1,2) + SUBSTR(TMP5,TMP2,2)
RETURN(HSENHA)

FUNCTION MOLDURA
PRIVATE Y1,X1,Y2,X2,TIT,CORFND,CORTIT,CONANT,TP,SH
PARAMETERS Y1,X1,Y2,X2,CORFND,TP,TIT,CORTIT,SH
TP = IF(TYPE("TP")="U",.F.,TP)
SH = IF(TYPE("SH")="U",.T.,SH)
CORANT = SETCOLOR(CORFND)
@ Y1,X1,Y2,X2 BOX IF(TP,"Ú","Ú")+"Ä¿³ÙÄÀ³ "
@ Y1,X1+1 SAY IF(TP,"Ä","Ä")
IF TP
   SETCOLOR(CORTIT)
   @ Y1,X1+2 SAY ALIGN(TIT,"C",X2-X1-3)
ENDIF
IF SH
   BORDER(Y1,X1,Y2,X2)
ENDIF
SETCOLOR(CORANT)
RETURN(.T.)

FUNCTION MESSAGE
PRIVATE STR,CORANT,COR
PARAMETERS STR,COR
STR    = IF(TYPE("STR")="U",SPACE(67),STR)
@ 23,02 SAY SPACE(67)
CORANT = SETCOLOR(IF(TYPE("COR")="U",STDMOLD,COR))
@ 23,02 SAY STR
SETCOLOR(CORANT)
RETURN(.T.)

FUNCTION WARNING
PRIVATE STR
PARAMETERS STR
CLEAR SCREEN
? STR
?
QUIT
RETURN(.F.)

FUNCTION CONFIRM
PARAMETERS TEXTO,PADRAO
CORANT3 = SETCOLOR(STDMOLD+","+STDINVE)
OPC = IF(TYPE("PADRAO")="U",1,IF(PADRAO,1,2))
@ 23,01 SAY TEXTO
@ 23,COL()+3 PROMPT "  Sim  "
@ 23,COL()+3 PROMPT "  N„o  "
MENU TO OPC
@ 23,01 SAY SPACE(78)
SETCOLOR(CORANT3)
RETURN(OPC = 1)

FUNCTION EXTRATO
PRIVATE NCONTA,PARLOGICO
PARAMETER NCONTA,PARLOGICO
HNOME     = NOME
HCREDITO  = CREDITO
HBLOQUEIO = BLOQUEIO
HTIPOPGTO = TIPOPGTO
STOTAL    = 0
LIN       = 1
SELECT LANCAMEN
SET ORDER TO 2
GO TOP
KPRINT(@LIN,00,CHR(14)+"EXTRATO")
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,"Numero: " + NCONTA)
KPRINT(@LIN,00,"Nome..: " + HNOME)
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,"DATA |QTD|PRO-|VALOR DO")
KPRINT(@LIN,00,"PED. |   |DUTO|PEDIDO  ")
KPRINT(@LIN,00,"-----+---+----+--------")
DO WHILE .NOT. EOF()
   IF &PARLOGICO
      STOTAL = STOTAL + VALOR
      KPRINT(@LIN,00,STRZERO(DAY  (DATALCTO),2,0)+"/"+;
                     STRZERO(MONTH(DATALCTO),2,0)+"|"+;
                     STRZERO(QTDPROD        ,3,0)+"| "+;
                     STRZERO(VAL(CODPROD)   ,3,0)+"|" +;
                     TRANSFORM(VALOR,"9,999.99"))
   ENDIF
   SKIP +1
ENDDO
TOTAL = STOTAL - HCREDITO
KPRINT(@LIN,00,"               --------")
KPRINT(@LIN,00,"Sub-Total:     "+TRANSFORM(STOTAL        ,"9,999.99"))
KPRINT(@LIN,00,"Credito..:     "+TRANSFORM(HCREDITO      ,"9,999.99"))
KPRINT(@LIN,00,"               --------")
KPRINT(@LIN,00,"Total....:     "+TRANSFORM(TOTAL,"9,999.99"))
KPRINT(@LIN,00,"")
KPRINT(@LIN,00,"Deve a "+STRZERO(INT(HBLOQUEIO/2),2,0)+" semana(s)")
KPRINT(@LIN,00,"Tipo Pgto.: "+HTIPOPGTO)
KPRINT(@LIN,00,"")
KRODAP(@LIN)
RETURN(.T.)
